name: Unit Tests # Name of the workflow

on:
  push:
    branches: [dev] # Trigger on push to the dev branch
  pull_request:
    branches: [dev] # Trigger on pull requests to the dev branch

jobs: # Defines the jobs that will run as part of this workflow
  tests: # Name of the job, useful for identifying the check in branch protection
    runs-on: ubuntu-latest # Runs on the latest Ubuntu image on GitHub's servers

    steps:
      - uses: actions/checkout@v3 # Check out the repository code

      - name: Install Dependencies
        run: cd my-app && npm install # Installs the dependencies

      - name: Unit Test
        run: cd my-app && npm test # Runs your unit tests
